import { Injectable } from "@angular/core";
import { NzMessageService } from "ng-zorro-antd";

@Injectable({
  providedIn: "root"
})
export class CommonService {
  APIUrl = "http://127.0.0.1:81/api/";
  AuthUrl = this.APIUrl + "auth/login";
  APIEndPoint = this.APIUrl + "api";
  StudantUrl = this.APIEndPoint + "/studant";
  StudantBasicUrl = this.APIEndPoint + "/studant/basic";
  AcceptanceUrl = this.StudantUrl + "/acceptance";
  Registration = this.StudantUrl + "/registration";
  Scolarship = this.StudantUrl + "/scolarship";
  Payment = this.StudantUrl + "/payment";
  Pass = this.StudantUrl + "/pass";
  repeat = this.StudantUrl + "/repeat"; 
  freeze= this.StudantUrl + "/freeze";
  unfreeze= this.StudantUrl + "/unfreeze";
  resign= this.StudantUrl + "/resign";
  resignStatement= this.StudantUrl + "/resignStatement";
  transfare= this.StudantUrl + "/transfare";
  cardReplacement= this.StudantUrl + "/cardReplacement";
  installment = this.APIEndPoint + "/installment";
  transactions = this.APIEndPoint + "/transactions";
  reports = this.APIEndPoint + "/reports/print";
  settings = this.APIEndPoint + "/settings";
  users = this.APIEndPoint + "/users";
  services = this.APIEndPoint + "/services";

  tolls = this.APIEndPoint + "/tolls";
  user = this.settings + "/user";
  toll = this.settings + "/toll";
  order= this.APIEndPoint + "/order";
  extrapayments= this.APIEndPoint + "/extra";

  constructor(public msg: NzMessageService) {}

  roles: Role = {
    acceptance: false,
    approval: false,
    registration: false,
    scolarship: false,
    installment: false,
    exams: false,
    settings: false
  };

  Country = [
    { value: "اثيوبيا", label: "اثيوبيا" },
    { value: "اذربيجان", label: "اذربيجان" },
    { value: "ارمينيا", label: "ارمينيا" },
    { value: "اريتريا", label: "اريتريا" },
    { value: "استراليا", label: "استراليا" },
    { value: "استونيا", label: "استونيا" },
    { value: "اسرائيل", label: "اسرائيل" },
    { value: "افغانستان", label: "افغانستان" },
    { value: "الارجنتين", label: "الارجنتين" },
    { value: "الاردن", label: "الاردن" },
    { value: "الاكوادور", label: "الاكوادور" },
    { value: "الامارات العربية المتحدة", label: "الامارات العربية المتحدة" },
    { value: "البانيا", label: "البانيا" },
    { value: "البحرين", label: "البحرين" },
    { value: "البرازيل", label: "البرازيل" },
    { value: "البرتغال", label: "البرتغال" },
    { value: "البوسنةوالهرسك", label: "البوسنةوالهرسك" },
    { value: "الجزائر", label: "الجزائر" },
    { value: "الدنمارك", label: "الدنمارك" },
    { value: "الدومينيكان", label: "الدومينيكان" },
    { value: "الرأسالاخضر", label: "الرأسالاخضر" },
    { value: "السعودية", label: "السعودية" },
    { value: "السلفادور", label: "السلفادور" },
    { value: "السنغال", label: "السنغال" },
    { value: "السودان", label: "السودان" },
    { value: "جنوب السودان", label: "جنوب السودان" },
    { value: "السويد", label: "السويد" },
    { value: "الصومال", label: "الصومال" },
    { value: "الصين", label: "الصين" },
    { value: "العراق", label: "العراق" },
    { value: "الغابون", label: "الغابون" },
    { value: "الفاتيكان", label: "الفاتيكان" },
    { value: "الفليبين", label: "الفليبين" },
    { value: "الكاميرون", label: "الكاميرون" },
    { value: "الكويت", label: "الكويت" },
    { value: "المانيا", label: "المانيا" },
    { value: "المجر", label: "المجر" },
    { value: "المغرب", label: "المغرب" },
    { value: "المكسيك", label: "المكسيك" },
    { value: "المملكة المتحدة", label: "المملكة المتحدة" },
    { value: "النرويج", label: "النرويج" },
    { value: "النمسا", label: "النمسا" },
    { value: "النيجر", label: "النيجر" },
    { value: "الهند", label: "الهند" },
    {
      value: "الولايات المتحدة الامريكية",
      label: "الولايات المتحدة الامريكية"
    },
    { value: "اليابان", label: "اليابان" },
    { value: "اليمن", label: "اليمن" },
    { value: "اليونان", label: "اليونان" },
    { value: "امارة موناكو", label: "امارة موناكو" },
    { value: "انتيغواوباربودا", label: "انتيغواوباربودا" },
    { value: "اندورا", label: "اندورا" },
    { value: "اندونيسيا", label: "اندونيسيا" },
    { value: "انغولا", label: "انغولا" },
    { value: "اورغواي", label: "اورغواي" },
    { value: "اوزباكستان", label: "اوزباكستان" },
    { value: "اوغندا", label: "اوغندا" },
    { value: "اوكرانيا", label: "اوكرانيا" },
    { value: "ايران", label: "ايران" },
    { value: "ايرلندا", label: "ايرلندا" },
    { value: "ايسلندا", label: "ايسلندا" },
    { value: "ايطاليا", label: "ايطاليا" },
    { value: "إسبانيا", label: "إسبانيا" },
    { value: "بابوا غينيا الجديدة", label: "بابوا غينيا الجديدة" },
    { value: "باراغواي", label: "باراغواي" },
    { value: "باربادوس", label: "باربادوس" },
    { value: "باكستان", label: "باكستان" },
    { value: "بالو", label: "بالو" },
    { value: "بروناى", label: "بروناى" },
    { value: "بلجيكا", label: "بلجيكا" },
    { value: "بلغاريا", label: "بلغاريا" },
    { value: "بنغلاديش", label: "بنغلاديش" },
    { value: "بنما", label: "بنما" },
    { value: "بنين", label: "بنين" },
    { value: "بوتان", label: "بوتان" },
    { value: "بوتسوانا", label: "بوتسوانا" },
    { value: "بوركينافاسو", label: "بوركينافاسو" },
    { value: "بوركينافاسو", label: "بوركينافاسو" },
    { value: "بورما", label: "بورما" },
    { value: "بوروندي", label: "بوروندي" },
    { value: "بولندا", label: "بولندا" },
    { value: "بوليفيا", label: "بوليفيا" },
    { value: "بيرو", label: "بيرو" },
    { value: "بيلاروسيا", label: "بيلاروسيا" },
    { value: "بيليز", label: "بيليز" },
    { value: "تايلاند", label: "تايلاند" },
    { value: "تركمانستان", label: "تركمانستان" },
    { value: "تركيا", label: "تركيا" },
    { value: "ترينداد وتوباغو", label: "ترينداد وتوباغو" },
    { value: "تشاد", label: "تشاد" },
    { value: "تنزانيا", label: "تنزانيا" },
    { value: "توغو", label: "توغو" },
    { value: "توفالو", label: "توفالو" },
    { value: "تـونس", label: "تـونس" },
    { value: "تونغا", label: "تونغا" },
    { value: "تيمورالشرقية", label: "تيمورالشرقية" },
    { value: "جاميكا", label: "جاميكا" },
    { value: "جزر المالديف", label: "جزر المالديف" },
    { value: "جزر سولومون", label: "جزر سولومون" },
    { value: "جزر سيشل", label: "جزر سيشل" },
    { value: "جزر مارشال", label: "جزر مارشال" },
    { value: "جزر مايكرونيزيا", label: "جزر مايكرونيزيا" },
    { value: "جزرالُقمـــر", label: "جزرالُقمـــر" },
    { value: "جزرالبهاما", label: "جزرالبهاما" },
    { value: "جزرفيجي", label: "جزرفيجي" },
    { value: "جزيرة مالطا", label: "جزيرة مالطا" },
    { value: "جمهوريةافريقياالوسطى", label: "جمهوريةافريقياالوسطى" },
    { value: "جمهوريةالتشيك", label: "جمهوريةالتشيك" },
    { value: "جمهوريةالكونغو", label: "جمهوريةالكونغو" },
    { value: "جمهوريةالكونغوالديمقراطية", label: "جمهوريةالكونغوالديمقراطية" },
    { value: "جنوب افريقيا", label: "جنوب افريقيا" },
    { value: "جورجيا", label: "جورجيا" },
    { value: "جيبوتي", label: "جيبوتي" },
    { value: "دومينيكا", label: "دومينيكا" },
    { value: "رواندا", label: "رواندا" },
    { value: "روسيا الاتحادية", label: "روسيا الاتحادية" },
    { value: "رومانيا", label: "رومانيا" },
    { value: "زامبيا", label: "زامبيا" },
    { value: "زيمبابوى", label: "زيمبابوى" },
    { value: "ساحلالعاج", label: "ساحلالعاج" },
    { value: "ساموا", label: "ساموا" },
    { value: "سان فنسن وغرينادينز", label: "سان فنسن وغرينادينز" },
    { value: "سان كيتس اند نيفز", label: "سان كيتس اند نيفز" },
    { value: "سان لوتشيا", label: "سان لوتشيا" },
    { value: "سان مارينو", label: "سان مارينو" },
    { value: "ساوتومي اند برنسيب", label: "ساوتومي اند برنسيب" },
    { value: "سريلانكا", label: "سريلانكا" },
    { value: "سلطنة عًمان", label: "سلطنة عًمان" },
    { value: "سلوفاكيا", label: "سلوفاكيا" },
    { value: "سلوفينيا", label: "سلوفينيا" },
    { value: "سنغافورة", label: "سنغافورة" },
    { value: "سوازيلاند", label: "سوازيلاند" },
    { value: "سوريا", label: "سوريا" },
    { value: "سورينام", label: "سورينام" },
    { value: "سويسرا", label: "سويسرا" },
    { value: "سيراليون", label: "سيراليون" },
    { value: "شيلي", label: "شيلي" },
    { value: "صربيا", label: "صربيا" },
    { value: "طاجكستان", label: "طاجكستان" },
    { value: "غامبيا", label: "غامبيا" },
    { value: "غانا", label: "غانا" },
    { value: "غرانادا", label: "غرانادا" },
    { value: "غواتيمالا", label: "غواتيمالا" },
    { value: "غويانا", label: "غويانا" },
    { value: "غينيا", label: "غينيا" },
    { value: "غينيا بيساو", label: "غينيا بيساو" },
    { value: "غينياالاستوائية", label: "غينياالاستوائية" },
    { value: "فانواتو", label: "فانواتو" },
    { value: "فرنسا", label: "فرنسا" },
    { value: "فنزويلا", label: "فنزويلا" },
    { value: "فنلندا", label: "فنلندا" },
    { value: "فيتنام", label: "فيتنام" },
    { value: "قبرص", label: "قبرص" },
    { value: "قرغيزستان", label: "قرغيزستان" },
    { value: "قطر", label: "قطر" },
    { value: "كازاخستان", label: "كازاخستان" },
    { value: "كرواتيا", label: "كرواتيا" },
    { value: "كمبوديا", label: "كمبوديا" },
    { value: "كندا", label: "كندا" },
    { value: "كوبا", label: "كوبا" },
    { value: "كوريا الجنوبية", label: "كوريا الجنوبية" },
    { value: "كوريا الشمالية", label: "كوريا الشمالية" },
    { value: "كوستاريكا", label: "كوستاريكا" },
    { value: "كولمبيا", label: "كولمبيا" },
    { value: "كيريباتى", label: "كيريباتى" },
    { value: "كينيا", label: "كينيا" },
    { value: "لاتفيا", label: "لاتفيا" },
    { value: "لاوس", label: "لاوس" },
    { value: "لاوس", label: "لاوس" },
    { value: "لبنان", label: "لبنان" },
    { value: "لوكسمبورغ", label: "لوكسمبورغ" },
    { value: "ليبيا", label: "ليبيا" },
    { value: "ليبيريا", label: "ليبيريا" },
    { value: "ليختنشتاين", label: "ليختنشتاين" },
    { value: "مالاوى", label: "مالاوى" },
    { value: "مالى", label: "مالى" },
    { value: "ماليزيا", label: "ماليزيا" },
    { value: "مدغشقر", label: "مدغشقر" },
    { value: "مصر", label: "مصر" },
    { value: "مقدونيا", label: "مقدونيا" },
    { value: "منغولي", label: "منغولي" },
    { value: "موريتانيا", label: "موريتانيا" },
    { value: "موريشيوس", label: "موريشيوس" },
    { value: "موزمبيق", label: "موزمبيق" },
    { value: "مولدوفيا", label: "مولدوفيا" },
    { value: "مونتنيغرو", label: "مونتنيغرو" },
    { value: "ناميبيا", label: "ناميبيا" },
    { value: "ناورو", label: "ناورو" },
    { value: "نيبال", label: "نيبال" },
    { value: "نيجيريا", label: "نيجيريا" },
    { value: "نيكاراغوا", label: "نيكاراغوا" },
    { value: "نيوزيلندا", label: "نيوزيلندا" },
    { value: "هايتي", label: "هايتي" },
    { value: "هندوراس", label: "هندوراس" },
    { value: "هولندا", label: "هولندا" }
  ];

  Natoinality = [
    { value: "Afghans", label: "افغانى" },
    { value: "Albanian", label: "البانى" },
    { value: "Algerian", label: "جزائرى" },
    { value: "Angolan", label: "انجولى" },
    { value: "Argentinean", label: "ارجنتينى" },
    { value: "Armenian", label: "ارمينى" },
    { value: "Australian", label: "استرالى" },
    { value: "Austrian", label: "نمساوى" },
    { value: "Bahraini ", label: "بحرينى" },
    { value: "Bangladeshi", label: "بنجلاديشى" },
    { value: "Belgian", label: "بلجيكى" },
    { value: "Beninese", label: "بنينى" },
    { value: "Bolivian", label: "بوليفي" },
    { value: "Brazilian", label: "برازيلى" },
    { value: "British", label: "بريطاني" },
    { value: "Canadian", label: "كندي" },
    { value: "Chinese", label: "صيني" },
    { value: "Congolese", label: "كنغولي" },
    { value: "Croatian", label: "كرواتي" },
    { value: "Danish", label: "دنماركي" },
    { value: "Ecuadorean", label: "اكوادوري" },
    { value: "Egyptian", label: "مصري" },
    { value: "Estonian", label: "ايستواني" },
    { value: "Finnish", label: "فلندي" },
    { value: "French", label: "فرنسي" },
    { value: "Gabonese", label: "جابونى" },
    { value: "Georgian", label: "جورجي" },
    { value: "German", label: "الماني" },
    { value: "Ghanaian", label: "غاني" },
    { value: "Greek", label: "يوناني" },
    { value: "Dutch", label: "هولندي" },
    { value: "Hungarian", label: "هنجاري" },
    { value: "Icelandic", label: "ايسلندي" },
    { value: "Indian", label: "هندي" },
    { value: "Indonesian", label: "اندونيسي" },
    { value: "Iranian", label: "ايراني" },
    { value: "Iraqi", label: "عراقي" },
    { value: "Irish", label: "ايرلندى" },
    { value: "Italian", label: "ايطالي" },
    { value: "Jamaican", label: "جاميكي" },
    { value: "Japanese", label: "ياباني" },
    { value: "Jordanian", label: "اردني" },
    { value: "Kenyan", label: "كيني" },
    { value: "Kuwaiti", label: "كويتي" },
    { value: "Lebanese", label: "لبناني" },
    { value: "Libyan", label: "ليبي" },
    { value: "Luxembourger", label: "لوكسمبورجي" },
    { value: "Malawian", label: "مالاوي" },
    { value: "Malaysian", label: "ماليزي" },
    { value: "Mauritanian", label: "موريتاني" },
    { value: "Mexican", label: "مكسيكي" },
    { value: "Moroccan", label: "مغربي" },
    { value: "Mozambican", label: "موزمبيقى" },
    { value: "Dutch", label: "هولندي" },
    { value: "New Zealander", label: "نيوزيلندي" },
    { value: "Nigerian", label: "نيجيري" },
    { value: "Norwegian", label: "نرويجي" },
    { value: "Omani", label: "عماني" },
    { value: "Pakistani", label: "باكستاني" },
    { value: "Palestinian", label: "فليسطيني" },
    { value: "Peruvian", label: "بيرو" },
    { value: "Philippine", label: "فليبيني" },
    { value: "Polish", label: "بولندي" },
    { value: "Portuguese", label: "برتغالي" },
    { value: "Qatari", label: "قطري" },
    { value: "Russian", label: "روسي" },
    { value: "Saudi Arabian", label: "سعودي" },
    { value: "Scottish", label: "اسكتلندي" },
    { value: "Singaporean", label: "سنغافوري" },
    { value: "Somali", label: "صومالي" },
    { value: "South African", label: "جنوب افريقي" },
    { value: "Spanish", label: "اسباني" },
    { value: "Sri Lankan", label: "سيرلانكي" },
    { value: "Sudanese", label: "سوداني" },
    { value: "South Sudanese", label: "جنوب سوداني" },
    { value: "Swedish", label: "سويدي" },
    { value: "Swiss", label: "سويسري" },
    { value: "Syrian", label: "سوري" },
    { value: "Taiwanese", label: "تايواني" },
    { value: "Thai", label: "تايلاندي" },
    { value: "Tunisian", label: "تونسي" },
    { value: "Turkish", label: "تركي" },
    { value: "Emirati", label: "اماراتي" },
    { value: "American", label: "امريكي" },
    { value: "Yemeni", label: "يمني" },
    { value: "Zambian", label: "زامبي" }
  ];
}

export interface Role {
  acceptance: boolean;
  approval: boolean;
  registration: boolean;
  scolarship: boolean;
  installment: boolean;
  exams: boolean;
  settings: boolean;
}
